// Job categories for Jigz marketplace
// Updated job categories database with 991 unique professional services
// Removed categories as per user request

export const jobCategories = [
  "All Categories",
  "Access Control",
  "Accessory Placement",
  "Accident Recovery",
  "Accountability",
  "Accounts Payable",
  "AC Install",
  "AC Repair",
  "Acrylic Nails",
  "Ad Copy",
  "Adult CPR",
  "AED Use",
  "Aerial Real Estate",
  "Affiliate Marketing",
  "Affiliate Recruitment",
  "After School Care",
  "Agility Training",
  "AI Model Development",
  "Alarm Check",
  "Alarm System Installation",
  "Algae Control",
  "Analytics Reporting",
  "Animal Boarding",
  "Animal Care",
  "Animal Cleaning",
  "Animal Control",
  "Animal Education",
  "Animal Exercise",
  "Animal Health Support",
  "Animal Housing",
  "Animal Training",
  "Antenna Installation",
  "Antique Refinishing",
  "Antique Restoration",
  "API Development",
  "API Integration",
  "Appliance Hookup",
  "Appliance Installation",
  "Appliance Repair",
  "Application Monitoring",
  "Aquatic Environment Care",
  "Aquarium Maintenance",
  "AR App Development",
  "AR/VR Development",
  "Architectural Plans",
  "Area Cleaning",
  "Area Tours",
  "Art Creation",
  "Art Display",
  "Art Framing",
  "Art Installation",
  "Articulation Therapy",
  "As Built Drawings",
  "Attic Insulation",
  "Audio Enhancement",
  "Audio Production",
  "Audio Transcription",
  "Audio/Visual Setup",
  "Audiobook Narration",
  "Authentication Systems",
  "Auto Body Repair",
  "Auto Detailing",
  "Auto Glass Tinting",
  "Auto Mechanic",
  "Automated Testing",
  "Automotive Tinting",
  "Automation Flows",
  "AWS Architecture",
  "Back-End Development",
  "Background Checks",
  "Backsplash Install",
  "Baking Services",
  "Balancing",
  "Ballet",
  "Bank Reconciliation",
  "Barrier Installation",
  "Barrier Setup",
  "Basic First Aid",
  "Basketball Coach",
  "Bath and Brush",
  "Bathroom Tiling",
  "Bathing Assistance",
  "Battery Jump",
  "Battery Replacement",
  "Bee Removal",
  "Beginner Lessons",
  "Bicycle Repair",
  "Big Data Processing",
  "Bike Repair",
  "Bike Service",
  "Blockchain Development",
  "Blog & Article Writing",
  "Blown-In Insulation",
  "Blueprint Creation",
  "Boat Repair",
  "Body Movement",
  "Body Training",
  "Body Work",
  "Book Ghostwriting",
  "Book Recording",
  "Bookkeeping & Accounting",
  "Bot Development",
  "Bouquet Design",
  "Brake Adjustment",
  "Brake Repair",
  "Brake Service",
  "Brand Development",
  "Brand Identity Design",
  "Brass Instrument Repair",
  "Brazilian Jiu-Jitsu",
  "Breathwork",
  "Brick Laying",
  "Brickwork",
  "Bridal Makeup",
  "Brochure Design",
  "Brushing and Bathing",
  "Budget Preparation",
  "Bug Control",
  "Bug Patching",
  "Bug Reporting",
  "Building Demolition",
  "Building Inspection",
  "Building Painting",
  "Building Washing",
  "Business Analysis",
  "Business Analytics",
  "Business Automation",
  "Business Card Design",
  "Business Intelligence",
  "Business Process Design",
  "Business Research",
  "Business Software",
  "Buttercream Art",
  "Cable Installation",
  "CAD Drafting (Remote)",
  "Cake Decorating",
  "Camera Install",
  "Camera Mounting",
  "Campaign Setup",
  "Canine Training",
  "Car Keys",
  "Car Repair",
  "Career Assessment",
  "Career Coaching",
  "Carpet Cleaning",
  "Carpet Installation",
  "Carpentry",
  "Cat Boarding",
  "Catering",
  "CCTV Installation",
  "Chain Repair",
  "Chair Repair",
  "Character Animation",
  "Character Illustration",
  "Character Poses",
  "Character Voices",
  "Chatbot Design",
  "Chatbot Development",
  "Chemical Balancing",
  "Childcare",
  "Chip Repair",
  "Chiropractic Services",
  "CI CD Pipeline",
  "Circuit Breaker Replacement",
  "City Walking Tours",
  "Climate Installation",
  "Climate Repair",
  "Clock Repair",
  "Closed Captions",
  "Closet Organizing",
  "Clothing Alteration",
  "Clothing Design",
  "Clothing Treatment",
  "Cloud Architecture",
  "Club DJ",
  "Code Testing",
  "Cold Precipitation Removal",
  "Color Selection",
  "Color Services",
  "Combat Training",
  "Commercial Mowing",
  "Commercial Voice Over",
  "Commission Structure",
  "Communication Bots",
  "Communication Device Repair",
  "Communication Equipment",
  "Communication Installation",
  "Communication Teaching",
  "Community Management",
  "Companionship",
  "Complete Development",
  "Computer Hardware Repair",
  "Computer Learning",
  "Computing Repair",
  "Concept Design",
  "Concrete Patios",
  "Concrete Work",
  "Construction Cleanup",
  "Construction Debris",
  "Construction Drawing",
  "Construction Flagging",
  "Construction Progress",
  "Consumer Research",
  "Contact Management",
  "Content Calendar",
  "Content Writing",
  "Conventional Oil",
  "Conversation Practice",
  "Conversational Flow",
  "Conversion Optimization",
  "Conversion Tracking",
  "Copywriting",
  "Core Training",
  "Corporate Events",
  "Corporate Presentations",
  "Corporate Videos",
  "Costume Construction",
  "Costume Design",
  "Courier Services (local)",
  "CPR Training",
  "Crack Sealing",
  "Creative Writing",
  "CRM Administration",
  "CRM Setup",
  "Cross Platform Apps",
  "Crown Reduction",
  "Crowd Control",
  "Cultural Education",
  "Custom Cabinets",
  "Custom Cakes",
  "Custom Engraving",
  "Custom Frames",
  "Custom Upholstery",
  "Customer Follow Up",
  "Customer Support (Live Chat)",
  "Cut and Trim",
  "Cybersecurity Assessment",
  "Cybersecurity Consulting",
  "Cycle Repair",
  "Daily Walks",
  "Dance Instruction",
  "Dashboard Automation",
  "Data Analysis",
  "Data Cleaning",
  "Data Engineering",
  "Data Entry",
  "Data Pipeline",
  "Data Processing",
  "Data Science & Analytics",
  "Data Visualization",
  "Database Administration",
  "Database Design",
  "Daycare Service",
  "DCF Modeling",
  "Deadwood Removal",
  "Debris Hauling",
  "Debris Removal",
  "Deck Building",
  "Deep Cleaning",
  "Deep Learning",
  "Deep Tissue",
  "Deer Deterrent",
  "DeFi Development",
  "Demolition",
  "Dent Removal",
  "Deployment Automation",
  "Design Consultation",
  "Desktop Publishing",
  "DevOps Engineering",
  "Dialog Polishing",
  "Diet Planning",
  "Digital Assets",
  "Digital Collectibles",
  "Digital Currency",
  "Digital Illustration",
  "Digital Marketing Strategy",
  "Digital Translation",
  "Dinner Parties",
  "Direct Marketing",
  "Disc Jockey (DJ)",
  "Dish Mounting",
  "Dishwasher Install",
  "Distribution",
  "Document Courier",
  "Document Formatting",
  "Document Translation",
  "Documentation",
  "Dog Boarding",
  "Dog Training",
  "Dog Walking",
  "Door Installation",
  "Downspout Flushing",
  "Drain Cleaning",
  "Dressing Help",
  "Dressage Training",
  "Driveway Installation",
  "Driveway Plowing",
  "Driveway Pouring",
  "Driveway Washing",
  "Drone Photography",
  "Dry Cleaning",
  "Dry Cleaning Pickup & Delivery",
  "Drywall Installation",
  "Drywall Patching",
  "Drywall Repair",
  "DVR Setup",
  "E Commerce Development",
  "Editorial Content",
  "Editing and Mastering",
  "Educational Services",
  "Educational Tours",
  "Elderly Care",
  "Electrical Panel Upgrade",
  "Electrical Repair",
  "Emergency Response Training",
  "Emergency Service",
  "Emergency Training",
  "Engine Diagnostics",
  "Engine Maintenance",
  "Engine Service",
  "English Spanish Translation",
  "English Tutoring",
  "Engraving Services",
  "Entertainment Software",
  "Entry Door",
  "Entry Installation",
  "Entry Screening",
  "Episode Planning",
  "Equipment Repair",
  "Equipment Service",
  "Equine Training",
  "Erection",
  "Errand Running",
  "ERP Consulting",
  "ESL Instruction",
  "Ethernet Cabling",
  "ETL Pipeline Development",
  "Event Barriers",
  "Event Coordination",
  "Event Parking",
  "Event Planning",
  "Event Security",
  "Event Servers",
  "Event Staff",
  "Event Videography",
  "Evening Babysitting",
  "Excel & Spreadsheet Automation",
  "Exercise Classes",
  "Exhibit Explanation",
  "Experience Design",
  "Explainer Videos",
  "Exterior Glass",
  "Exterior Painting",
  "Exterior Repair",
  "Exterior Wash",
  "Fabric Care",
  "Fabric Cleaning",
  "Fabric Repair",
  "Fact Checking",
  "Family Care",
  "Feature Development",
  "Feature Planning",
  "Fence Installation",
  "Fiber Pulling",
  "Fiction Narration",
  "Fighting Training",
  "Filter Maintenance",
  "Financial Modeling",
  "Financial Planning",
  "Financial Records",
  "Fire Alarm",
  "Fire Extinguisher Service",
  "Fire Safety Inspection",
  "First Aid Training",
  "Fish Tank Care",
  "Fitness Coaching (Online)",
  "Fitness Training",
  "Fixture Installation",
  "Flagging",
  "Flat Pack Assembly",
  "Floor Covering Installation",
  "Floor Installation",
  "Floor Safe",
  "Flooring",
  "Floral Arrangement",
  "Flower Service",
  "Fluency Therapy",
  "Flying Insect Removal",
  "Fondant Design",
  "Food Planning",
  "Food Service",
  "Foot Covering Repair",
  "Footwear Repair",
  "Formula Optimization",
  "Forum Moderation",
  "Foundation Repair",
  "Fountain Installation",
  "Fragile Packing",
  "Framing",
  "Freelance Writing",
  "Front-End Development",
  "Full Bar Service",
  "Full Service Planning",
  "Full Stack Development",
  "Full Time Nanny",
  "Full-Stack Development",
  "Functional Testing",
  "Funding Writing",
  "Furnace Install",
  "Furnace Repair",
  "Furniture Assembly",
  "Furniture Repair",
  "Furniture Rental",
  "Furniture Reupholstery",
  "Furniture Upholstery",
  "Game Design",
  "Game Development",
  "Garage Door Repair",
  "Garage Organizing",
  "Garbage Collection",
  "Garden Maintenance",
  "Garment Care",
  "Garment Modification",
  "Gas Optimization",
  "Gear Tuning",
  "Gel Manicure",
  "General Repairs",
  "Generator Service",
  "Generative Models",
  "Ghostwriting",
  "GIS Mapping & Analysis",
  "Glass Cleaning",
  "Glass Installation",
  "Glass Replacement",
  "Glass Tinting",
  "Goal Setting",
  "Google Ads Setup",
  "Government Forms",
  "Grammar Check",
  "Grant Research",
  "Grant Writing",
  "Graphic Design",
  "Grass Installation",
  "Grocery Runs",
  "Ground Covering",
  "Ground Installation",
  "Groundwork Training",
  "Group Direction",
  "Group Walks",
  "Growth Hacking",
  "Guard Service",
  "Guest Service",
  "Guest Vehicle Service",
  "Guided Meditation",
  "Guitar Lessons",
  "Gutter Cleaning",
  "Hair Service",
  "Hair Styling",
  "Haircut and Styling",
  "Haircuts",
  "Hand Care",
  "Hand Therapy",
  "Handyman Services",
  "Hanging Boards",
  "Hardware Setup",
  "Hardwood Install",
  "Hatha Yoga",
  "Heating Installation",
  "Hedge Trimming",
  "Heel Replacement",
  "Height Reduction",
  "Help Desk",
  "Help Services",
  "Hemming",
  "Hip-Hop",
  "Historical Tours",
  "Historic Restoration",
  "Hive Removal",
  "Hole Patching",
  "Home Inspection",
  "Home Organization",
  "Home Pickup",
  "Home Repairs",
  "Home Staging",
  "Homework Help",
  "Hoof Cleaning",
  "Horse Care",
  "Horse Grooming",
  "House Exterior Painting",
  "House Keys",
  "House Painting",
  "House Siding Wash",
  "Household Junk",
  "Household Waste",
  "HR Consulting & Recruitment",
  "HTML CSS Coding",
  "Hull Repair",
  "HVAC Installation",
  "HVAC Repair",
  "Icon Design",
  "Identity Design",
  "Ikea Assembly",
  "Illustration",
  "Image Capture",
  "In Home Sitting",
  "Income Tax Filing",
  "Incident Response",
  "Indie Game Development",
  "Infant Care",
  "Infant CPR",
  "Infographic Design",
  "Information Analysis",
  "Information Management",
  "Information Processing",
  "Information Study",
  "Infrastructure Management",
  "Insect Extermination",
  "Insect Removal",
  "Insights Report",
  "Inspection",
  "Installation",
  "Instrument Repair",
  "Instrument Tuning",
  "Insulation Installation",
  "Intelligence Development",
  "Interaction Design",
  "Interior Decorating",
  "Interior Demo",
  "Interior Door Hang",
  "Interior Glass",
  "Interior Painting",
  "Interior Shampoo",
  "Interview Prep",
  "Interview Transcription",
  "iOS Apps",
  "Ironing Services",
  "Irrigation System Installation",
  "IT Management",
  "IT On-Site Support",
  "Item Repair",
  "JavaScript Development",
  "Jewelry Repair",
  "Job Description Writing",
  "Joint Reinforcement",
  "Jump Starts",
  "Junk Removal",
  "Karate",
  "Key Cutting",
  "Key Service",
  "Keyword Research",
  "Keyword Strategy",
  "Kinetic Typography",
  "KPI Definition",
  "Lab Sample Collection",
  "Laminate Install",
  "Landing Page Copy",
  "Landscape Design",
  "Landscaping",
  "Language Service",
  "Language Tutoring",
  "Large Animal Care",
  "Launch Coordination",
  "Laundry Services",
  "Lawn Mower Repair",
  "Lawn Mowing",
  "Lawn Service",
  "Layout Design",
  "Leak Repair",
  "Legal Transcription",
  "Leveling and EQ",
  "Life Coaching",
  "Life Saving Training",
  "Lighting Technician",
  "Link Building",
  "LinkedIn Profile",
  "Litter Box Cleaning",
  "Live Chat Support",
  "Living Plant Installation",
  "Load In",
  "Local Moves",
  "Local Towing",
  "Location Analysis",
  "Lock Installation",
  "Lock Rekeying",
  "Lock Service",
  "Locksmith Services",
  "Logo & Brand Identity Design",
  "Logo Design",
  "Long Distance Moves",
  "Long Form Articles",
  "Lube Service",
  "Machine Installation",
  "Machine Learning Engineering",
  "Machine Repair",
  "Maintenance Updates",
  "Makeup Artist",
  "Manicure Service",
  "Map Creation",
  "Marine Repair",
  "Market Analysis",
  "Market Research",
  "Marketing Copy",
  "Marketing Writing",
  "Marketplace Listing",
  "Martial Arts Coaching",
  "Masonry",
  "Massage Therapy",
  "Mat Pilates",
  "Material Disposal",
  "Material Repair",
  "Material Shaping",
  "Math Tutoring",
  "Meal Planning",
  "Meal Service",
  "Measuring and Cutting",
  "Mechanical Clock Repair",
  "Mechanical Drawings",
  "Medical Training",
  "Meditation Classes",
  "Memoirs",
  "Mental Wellness",
  "MERN Stack",
  "Meta Descriptions",
  "Metal Fabrication",
  "Metal Joining",
  "MIG Welding",
  "Migration Planning",
  "Mind Body Practice",
  "Mindfulness & Meditation Coaching",
  "Mobile App Development",
  "Mobile Phone Repair",
  "Mobility Assistance",
  "Model Deployment",
  "Model Training",
  "Money Management",
  "Monitoring Setup",
  "Motion Capture",
  "Motion Graphics",
  "Motherboard Repair",
  "Motor Repair",
  "Motorcycle Repair",
  "Motorcycle Service",
  "Mounting",
  "Movement Classes",
  "Movement Direction",
  "Movement Therapy",
  "Moving Services",
  "Music Entertainment",
  "Music Lessons",
  "Music Lessons (Online)",
  "Music Production",
  "Musical Repairs",
  "Musical Training",
  "Museum Docent",
  "Nail Technician",
  "Nanny Services",
  "Narration",
  "Native Apps",
  "Network Administration",
  "Network Cabling Installation",
  "Network Setup",
  "Network Troubleshooting",
  "Newsletter Design",
  "NFT Creation & Management",
  "NFT Minting",
  "NLP Models",
  "Noise Reduction",
  "Nutrition Coaching (Online)",
  "Obedience Training",
  "Object Repair",
  "Occupational Therapy",
  "Office Furniture Setup",
  "Office Support",
  "Oil Change Service",
  "Online Advertising",
  "Online Commerce",
  "Online Development",
  "Online Fitness",
  "Online Music Teaching",
  "Online Reputation",
  "Online Store Management",
  "Online Tutoring (Academic)",
  "Open House Hosting",
  "Opening Installation",
  "Opener Repair",
  "Opinion Pieces",
  "Outdoor Building",
  "Outdoor Flooring",
  "Overnight Care",
  "Package Transport",
  "Packing Services",
  "Panel Installation",
  "Panel Replacement",
  "Pants Hemming",
  "Parking Attendant",
  "Part Time Nanny",
  "Partner Marketing",
  "Partnership Marketing",
  "Pastry Catering",
  "Pastry Service",
  "Path Construction",
  "Patio Installation",
  "Patrol Services",
  "Pattern Making",
  "Pattern Matching",
  "Paver Patios",
  "Payment Gateway Integration",
  "Pay-Per-Click (PPC) Management",
  "PC Repair",
  "People Management",
  "Performance Art",
  "Performance Marketing",
  "Performance Tuning",
  "Personal Assistant",
  "Personal Care Assistant",
  "Personal Coaching",
  "Personal Development",
  "Personal Ornament Repair",
  "Personal Shopping",
  "Personal Tasks",
  "Personal Training",
  "Personal Yoga",
  "Pest Control",
  "Pest Elimination",
  "Pet Boarding",
  "Pet Care",
  "Pet Cleanup",
  "Pet Exercise",
  "Pet Grooming",
  "Pet Lodging",
  "Pet Sitting",
  "Pet Waste Management",
  "Pet Waste Removal",
  "Photo Services",
  "Photography",
  "Physical Therapy",
  "Piano Lessons",
  "Piano Tuning",
  "Picture Display",
  "Picture Framing",
  "Pilates Instruction",
  "Pipe Installation",
  "Pitch Decks",
  "Pitch Raise",
  "Plant Arrangement",
  "Plant Care",
  "Plant Installation",
  "Plant Maintenance",
  "Plated Dinner",
  "Platform Construction",
  "Plumbing",
  "Podcast Editing",
  "Podcast Production",
  "Policy Enforcement",
  "Pond Maintenance",
  "Pool Cleaning",
  "Pool Maintenance",
  "Portable Time Device Service",
  "Portrait Photography",
  "Post Construction",
  "Post Surgery Rehab",
  "Posture Correction",
  "Power Repair",
  "PPC Management",
  "Predictive Modeling",
  "Presentation & Slide Design",
  "Pressure Treated Decks",
  "Pressure Washing",
  "Print Design",
  "Private Chef",
  "Problem Solving",
  "Process Analysis",
  "Process Mapping",
  "Product Descriptions",
  "Product Management",
  "Product Modeling",
  "Product Photography",
  "Product Visualization",
  "Programming",
  "Progress Reporting",
  "Progress Tracking",
  "Project Management",
  "Project Planning",
  "Projector Setup",
  "Promotional Strategy",
  "Proofreading & Editing",
  "Property Arrangement",
  "Property Display",
  "Property Inspection",
  "Property Mowing",
  "Property Staging",
  "Property Tours",
  "Property Walkthrough",
  "Protection Installation",
  "Protection Services",
  "Pruning",
  "Publication Design",
  "Publication Writing",
  "Puppy Training",
  "QA Testing",
  "Quality Assurance (QA) Testing",
  "QuickBooks Setup",
  "Raccoon Removal",
  "Rain System Cleaning",
  "RAM Upgrade",
  "React Development",
  "Real Estate Showing Agent",
  "Reality Development",
  "Reception Equipment",
  "Recipe Ideas",
  "Recharge",
  "Recycling Pickup",
  "Refrigerator Repair",
  "Reformer Pilates",
  "Relocation Services",
  "Remote Music Teaching",
  "Remote Support",
  "Renewable Energy",
  "Replacement Windows",
  "Reporting Dashboards",
  "Reptile Control",
  "Reptile Removal",
  "Requirement Gathering",
  "Requirements Analysis",
  "Residential Mowing",
  "RESTful APIs",
  "Restoration Service",
  "Resume & CV Writing",
  "Resume Writing",
  "Retention Strategies",
  "Ring Resizing",
  "Roadmap Planning",
  "Roadside Assistance",
  "Robotic Process Automation (RPA) Development",
  "Rodent Control",
  "ROI Assessment",
  "Roof Antenna",
  "Roof Cleaning",
  "Roof Inspection",
  "Roof Replacement",
  "Roof Service",
  "Roofing",
  "Room Design",
  "RPA Development",
  "Rug Installation",
  "Safe Installation",
  "Safety Equipment",
  "Safety Equipment Service",
  "Safety Management",
  "Safety Systems",
  "Sales Copy",
  "Sales Pages",
  "Same Day Delivery",
  "Satellite Dish Installation",
  "Scaffolding Setup",
  "Scene Sketches",
  "Scenic Painting",
  "Screen Replacement",
  "Screenplays",
  "Scriptwriting",
  "Search Engine Optimization (SEO)",
  "Seating Repair",
  "Seating Restoration",
  "Security Audit",
  "Security Guard Services",
  "Security Installation",
  "Security Management",
  "Security Service",
  "Security Storage",
  "Security System Installation",
  "Sensor Placement",
  "SEO Content Writing",
  "SEO Writing",
  "Server Development",
  "Service Integration",
  "Service Staff",
  "Set Construction",
  "Set Design",
  "Sewing Services",
  "Shaping Services",
  "Shed Removal",
  "Sheet Metal Bending",
  "Shingle Replacement",
  "Shipping API",
  "Shirt Pressing",
  "Shoe Repair",
  "Shopify Setup",
  "Shower Tiling",
  "Signal Booster",
  "Signal Equipment",
  "Signal Reception",
  "Signature Cocktails",
  "Site Assessment",
  "Site Cleanup",
  "Site Selection",
  "Skimming Service",
  "Sky Photography",
  "Small Engine Repair",
  "Small Repairs",
  "Smart Contract Coding",
  "Smart Contract Development",
  "Snake Catching",
  "Snake Identification",
  "Snake Removal",
  "Snow Removal",
  "Soccer Coach",
  "Social Media Management",
  "Social Parties",
  "Social Strategy",
  "Sod Installation",
  "Sofa Reupholstery",
  "Software Architecture",
  "Software Engineering",
  "Software Testing & Bug Fixing",
  "Software Troubleshooting",
  "Solar Panel Installation",
  "Sole Repair",
  "Solidity Contracts",
  "Sound Design & Mixing",
  "Sound Effects",
  "Sound Entertainment",
  "Sound Equipment",
  "Sound Equipment Repair",
  "Sound Setup",
  "Sound System Rental",
  "Sound Training",
  "Space Organization",
  "Space Planning",
  "Spatial Analysis",
  "Special Effects",
  "Speech Therapy",
  "Spinal Adjustment",
  "Sports Coaching",
  "Sports Injury Rehab",
  "Spray Foam",
  "Sprinkler Inspection",
  "Sprinkler Setup",
  "Stage Crew",
  "Stage Design",
  "Stage Lighting",
  "Stage Lighting Design",
  "Stagehand",
  "Stain Removal",
  "Standard Tuning",
  "Statistical Modeling",
  "Steam Cleaning",
  "Steam Pressing",
  "Stone Installation",
  "Stone Veneer",
  "Storage Installation",
  "Storage Organization",
  "Store Optimization",
  "Storyboard Art",
  "Storyboarding",
  "Story Reading",
  "Story Visualization",
  "Story Writing",
  "Strength Training",
  "String Instrument Repair",
  "Stroke Improvement",
  "Structure Assessment",
  "Structure Removal",
  "Structure Repair",
  "Subject Tutoring",
  "Subtitle Addition",
  "Subtitle Sync",
  "Subtitling & Captioning",
  "Support Structure",
  "Surface Cleaning",
  "Surface Installation",
  "Surface Marking",
  "Surface Prep",
  "Surface Repair",
  "Surveillance",
  "Survey Design",
  "Swarm Relocation",
  "Swedish Massage",
  "Swim Instruction",
  "Synthetic Oil",
  "System Architecture",
  "System Design",
  "System Integration",
  "System Management",
  "System Updates",
  "Tailoring",
  "Talent Acquisition",
  "Taping and Mudding",
  "Task Automation",
  "Task Management",
  "Task Service",
  "Tax Preparation & Advice",
  "Technical Drawing (Digital)",
  "Technical Illustration",
  "Technical SEO",
  "Technical Support",
  "Technical Writing",
  "Technology Assistance",
  "Technology Design",
  "Technology Support",
  "Template Creation",
  "Template Design",
  "Temporary Vehicle Care",
  "Text Conversion",
  "Text Review",
  "Texture Matching",
  "Therapeutic Massage",
  "Thermal Installation",
  "Third Party Integration",
  "TIG Welding",
  "Tile Setting",
  "Time Device Repair",
  "Timepiece Repair",
  "Timepiece Service",
  "Tire Installation",
  "Token Creation",
  "Tour Guide",
  "Tow Truck Service",
  "Traffic Control",
  "Training and Support",
  "Transcription",
  "Translation",
  "Transparency Treatment",
  "Transplanting",
  "Transport Service",
  "Transportation Service",
  "Trash Pickup",
  "Travel Guide",
  "Tree Planting",
  "Tree Removal",
  "Tree Trimming",
  "Trophy Engraving",
  "UI Development",
  "UI Optimization",
  "Unit Testing",
  "Upholstery Repair",
  "User Experience",
  "User Manuals",
  "User Research",
  "User Testing",
  "UX/UI Design",
  "Valuation Models",
  "Valet Parking",
  "Vehicle Cleaning",
  "Vehicle Greeting",
  "Vehicle Movement",
  "Vehicle Repair",
  "Vehicle Retrieval",
  "Vehicle Service",
  "Vehicle Transport",
  "Veterinary Technician",
  "Video Animation",
  "Video Captions",
  "Video Editing",
  "Video Production",
  "Video Services",
  "Video Workouts",
  "Videography",
  "Vinyasa Flow",
  "Virtual Assistance",
  "Virtual Piano Lessons",
  "Vital Sign Monitoring",
  "Vocal Coaching",
  "Voice Acting",
  "Voice Therapy",
  "VPN Management",
  "VR Experience Design",
  "Vulnerability Assessment",
  "Waitstaff Services",
  "Wall Covering",
  "Wall Decoration",
  "Wall Hanging",
  "Wall Installation",
  "Wall Repair",
  "Wall Safe",
  "Wall Stabilization",
  "Wall Tiling",
  "Wallpaper Installation",
  "Wardrobe Design",
  "Wash and Fold",
  "Wash and Press",
  "Washer Repair",
  "Washer Setup",
  "Waste Disposal",
  "Watch Battery",
  "Watch Repair",
  "Water Change",
  "Water Cleaning",
  "Water Feature Care",
  "Water Garden Care",
  "Water Installation",
  "Water Repair",
  "Water Training",
  "Water Vehicle Repair",
  "Watering Systems",
  "Weather Removal",
  "Web Development",
  "Website Build",
  "Website Copy",
  "Website Localization",
  "Website Optimization",
  "Wedding DJ",
  "Wedding Florals",
  "Wedding Planning",
  "Weeding",
  "Weekly Meal Prep",
  "Weight Loss Coaching",
  "Welding",
  "Wellness Coaching",
  "Wheel Installation",
  "Wheel Service",
  "White Papers",
  "Whiteboard Animation",
  "Wild Animal Management",
  "Wilderness First Aid",
  "Wildlife Control",
  "Window Cleaning",
  "Window Installation",
  "Window Service",
  "Window Tinting",
  "Windshield Install",
  "Windshield Replacement",
  "Wired Alarm",
  "Wireless Alarm",
  "Wiring Fix",
  "Wood Construction",
  "Wood Fence",
  "Wood Refinishing",
  "Woodwork",
  "Work Therapy",
  "Workflow Automation",
  "Workplace Ergonomics",
  "Writing Service",
  "Written Content",
  "Yard Scooping",
  "Yoga Instruction",
  "Youth Care",
  "Youth Supervision",
  "eCommerce Store Setup & Management"
];

// Export categories without "All Categories" for specific use cases
export const categoriesWithoutAll = jobCategories.filter(category => category !== "All Categories");