runtime: nodejs18

# Environment variables for Google Cloud App Engine
env_variables:
  NODE_ENV: production

# Automatic scaling configuration  
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.7

# Resource allocation
resources:
  cpu: 1
  memory_gb: 2

# Static file handling
handlers:
- url: /attached_assets
  static_dir: attached_assets
  secure: always

- url: /uploads  
  static_dir: uploads
  secure: always

- url: /.*
  script: auto
  secure: always